/* soapremcudaProxy.h
   Generated by gSOAP 2.8.11 from remcuda.h

Copyright(C) 2000-2012, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
1) GPL or 2) Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapremcudaProxy_H
#define soapremcudaProxy_H
#include "soapH.h"
class remcuda
{   public:
	/// Runtime engine context allocated in constructor
	struct soap *soap;
	/// Endpoint URL of service 'remcuda' (change as needed)
	const char *endpoint;
	/// Constructor allocates soap engine context, sets default endpoint URL, and sets namespace mapping table
	remcuda()
	{ soap = soap_new(); endpoint = "http://127.0.0.1:161952"; if (soap && !soap->namespaces) { static const struct Namespace namespaces[] = 
{
	{"SOAP-ENV", "http://schemas.xmlsoap.org/soap/envelope/", "http://www.w3.org/*/soap-envelope", NULL},
	{"SOAP-ENC", "http://schemas.xmlsoap.org/soap/encoding/", "http://www.w3.org/*/soap-encoding", NULL},
	{"xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL},
	{"xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL},
	{"ns", "urn:remcuda", NULL, NULL},
	{NULL, NULL, NULL, NULL}
};
	soap->namespaces = namespaces; } };
	/// Destructor frees deserialized data and soap engine context
	virtual ~remcuda() { if (soap) { soap_destroy(soap); soap_end(soap); soap_free(soap); } };
	/// Invoke 'sum' of service 'remcuda' and return error code (or SOAP_OK)
	virtual int ns__sum(struct _rcArray v1, struct _rcArray v2, struct _rcArray *result) { return soap ? soap_call_ns__sum(soap, endpoint, NULL, v1, v2, result) : SOAP_EOM; };
	/// Invoke 'InnerProduct' of service 'remcuda' and return error code (or SOAP_OK)
	virtual int ns__InnerProduct(struct _rcArray v1, struct _rcArray v2, float *result) { return soap ? soap_call_ns__InnerProduct(soap, endpoint, NULL, v1, v2, result) : SOAP_EOM; };
};
#endif
