/* soapServer.cpp
   Generated by gSOAP 2.8.11 from remcuda.h

Copyright(C) 2000-2012, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
1) GPL or 2) Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "soapH.h"

SOAP_SOURCE_STAMP("@(#) soapServer.cpp ver 2.8.11 2013-12-12 06:49:41 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_serve(struct soap *soap)
{
#ifndef WITH_FASTCGI
	unsigned int k = soap->max_keep_alive;
#endif
	do
	{
#ifndef WITH_FASTCGI
		if (soap->max_keep_alive > 0 && !--k)
			soap->keep_alive = 0;
#endif
		if (soap_begin_serve(soap))
		{	if (soap->error >= SOAP_STOP)
				continue;
			return soap->error;
		}
		if (soap_serve_request(soap) || (soap->fserveloop && soap->fserveloop(soap)))
		{
#ifdef WITH_FASTCGI
			soap_send_fault(soap);
#else
			return soap_send_fault(soap);
#endif
		}

#ifdef WITH_FASTCGI
		soap_destroy(soap);
		soap_end(soap);
	} while (1);
#else
	} while (soap->keep_alive);
#endif
	return SOAP_OK;
}

#ifndef WITH_NOSERVEREQUEST
SOAP_FMAC5 int SOAP_FMAC6 soap_serve_request(struct soap *soap)
{
	soap_peek_element(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:sum"))
		return soap_serve_ns__sum(soap);
	if (!soap_match_tag(soap, soap->tag, "ns:InnerProduct"))
		return soap_serve_ns__InnerProduct(soap);
	return soap->error = SOAP_NO_METHOD;
}
#endif

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__sum(struct soap *soap)
{	struct ns__sum soap_tmp_ns__sum;
	struct ns__sumResponse soap_tmp_ns__sumResponse;
	struct _rcArray soap_tmp__rcArray;
	soap_default_ns__sumResponse(soap, &soap_tmp_ns__sumResponse);
	soap_default__rcArray(soap, &soap_tmp__rcArray);
	soap_tmp_ns__sumResponse.result = &soap_tmp__rcArray;
	soap_default_ns__sum(soap, &soap_tmp_ns__sum);
	soap->encodingStyle = NULL;
	if (!soap_get_ns__sum(soap, &soap_tmp_ns__sum, "ns:sum", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__sum(soap, soap_tmp_ns__sum.v1, soap_tmp_ns__sum.v2, soap_tmp_ns__sumResponse.result);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns__sumResponse(soap, &soap_tmp_ns__sumResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__sumResponse(soap, &soap_tmp_ns__sumResponse, "ns:sumResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__sumResponse(soap, &soap_tmp_ns__sumResponse, "ns:sumResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__InnerProduct(struct soap *soap)
{	struct ns__InnerProduct soap_tmp_ns__InnerProduct;
	struct ns__InnerProductResponse soap_tmp_ns__InnerProductResponse;
	float soap_tmp_float;
	soap_default_ns__InnerProductResponse(soap, &soap_tmp_ns__InnerProductResponse);
	soap_default_float(soap, &soap_tmp_float);
	soap_tmp_ns__InnerProductResponse.result = &soap_tmp_float;
	soap_default_ns__InnerProduct(soap, &soap_tmp_ns__InnerProduct);
	soap->encodingStyle = NULL;
	if (!soap_get_ns__InnerProduct(soap, &soap_tmp_ns__InnerProduct, "ns:InnerProduct", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = ns__InnerProduct(soap, soap_tmp_ns__InnerProduct.v1, soap_tmp_ns__InnerProduct.v2, soap_tmp_ns__InnerProductResponse.result);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	soap_serialize_ns__InnerProductResponse(soap, &soap_tmp_ns__InnerProductResponse);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put_ns__InnerProductResponse(soap, &soap_tmp_ns__InnerProductResponse, "ns:InnerProductResponse", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put_ns__InnerProductResponse(soap, &soap_tmp_ns__InnerProductResponse, "ns:InnerProductResponse", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of soapServer.cpp */
