/* soapStub.h
   Generated by gSOAP 2.8.11 from remcuda.h

Copyright(C) 2000-2012, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
1) GPL or 2) Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapStub_H
#define soapStub_H
#include "stdsoap2.h"
#if GSOAP_VERSION != 20811
# error "GSOAP VERSION MISMATCH IN GENERATED CODE: PLEASE REINSTALL PACKAGE"
#endif


/******************************************************************************\
 *                                                                            *
 * Enumerations                                                               *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Types with Custom Serializers                                              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Classes and Structs                                                        *
 *                                                                            *
\******************************************************************************/


#if 0 /* volatile type: do not declare here, declared elsewhere */

#endif

#ifndef SOAP_TYPE__rcArray
#define SOAP_TYPE__rcArray (7)
/* SOAP encoded array of xsd:float schema type: */
struct _rcArray
{
public:
	float *__ptr;
	int __size;
};
#endif

#ifndef SOAP_TYPE_ns__sumResponse
#define SOAP_TYPE_ns__sumResponse (12)
/* ns:sumResponse */
struct ns__sumResponse
{
public:
	struct _rcArray *result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ArrayOffloat */
};
#endif

#ifndef SOAP_TYPE_ns__sum
#define SOAP_TYPE_ns__sum (13)
/* ns:sum */
struct ns__sum
{
public:
	struct _rcArray v1;	/* required element of type ArrayOffloat */
	struct _rcArray v2;	/* required element of type ArrayOffloat */
};
#endif

#ifndef SOAP_TYPE_ns__InnerProductResponse
#define SOAP_TYPE_ns__InnerProductResponse (15)
/* ns:InnerProductResponse */
struct ns__InnerProductResponse
{
public:
	float *result;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type xsd:float */
};
#endif

#ifndef SOAP_TYPE_ns__InnerProduct
#define SOAP_TYPE_ns__InnerProduct (16)
/* ns:InnerProduct */
struct ns__InnerProduct
{
public:
	struct _rcArray v1;	/* required element of type ArrayOffloat */
	struct _rcArray v2;	/* required element of type ArrayOffloat */
};
#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (17)
/* SOAP Header: */
struct SOAP_ENV__Header
{
#ifdef WITH_NOEMPTYSTRUCT
private:
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (18)
/* SOAP Fault Code: */
struct SOAP_ENV__Code
{
public:
	char *SOAP_ENV__Value;	/* optional element of type xsd:QName */
	struct SOAP_ENV__Code *SOAP_ENV__Subcode;	/* optional element of type SOAP-ENV:Code */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (20)
/* SOAP-ENV:Detail */
struct SOAP_ENV__Detail
{
public:
	char *__any;
	int __type;	/* any type of element <fault> (defined below) */
	void *fault;	/* transient */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (23)
/* SOAP-ENV:Reason */
struct SOAP_ENV__Reason
{
public:
	char *SOAP_ENV__Text;	/* optional element of type xsd:string */
};
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (24)
/* SOAP Fault: */
struct SOAP_ENV__Fault
{
public:
	char *faultcode;	/* optional element of type xsd:QName */
	char *faultstring;	/* optional element of type xsd:string */
	char *faultactor;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *detail;	/* optional element of type SOAP-ENV:Detail */
	struct SOAP_ENV__Code *SOAP_ENV__Code;	/* optional element of type SOAP-ENV:Code */
	struct SOAP_ENV__Reason *SOAP_ENV__Reason;	/* optional element of type SOAP-ENV:Reason */
	char *SOAP_ENV__Node;	/* optional element of type xsd:string */
	char *SOAP_ENV__Role;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *SOAP_ENV__Detail;	/* optional element of type SOAP-ENV:Detail */
};
#endif

#endif

/******************************************************************************\
 *                                                                            *
 * Typedefs                                                                   *
 *                                                                            *
\******************************************************************************/

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
typedef char *_QName;
#endif

#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (6)
typedef char *_XML;
#endif


/******************************************************************************\
 *                                                                            *
 * Externals                                                                  *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Server-Side Operations                                                     *
 *                                                                            *
\******************************************************************************/


SOAP_FMAC5 int SOAP_FMAC6 ns__sum(struct soap*, struct _rcArray v1, struct _rcArray v2, struct _rcArray *result);

SOAP_FMAC5 int SOAP_FMAC6 ns__InnerProduct(struct soap*, struct _rcArray v1, struct _rcArray v2, float *result);

/******************************************************************************\
 *                                                                            *
 * Server-Side Skeletons to Invoke Service Operations                         *
 *                                                                            *
\******************************************************************************/

SOAP_FMAC5 int SOAP_FMAC6 soap_serve(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_request(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__sum(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns__InnerProduct(struct soap*);

/******************************************************************************\
 *                                                                            *
 * Client-Side Call Stubs                                                     *
 *                                                                            *
\******************************************************************************/


SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__sum(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _rcArray v1, struct _rcArray v2, struct _rcArray *result);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns__InnerProduct(struct soap *soap, const char *soap_endpoint, const char *soap_action, struct _rcArray v1, struct _rcArray v2, float *result);

#endif

/* End of soapStub.h */
